language: node_js
node_js:
  - '15'
branches:
only:
  - master
  - develop
  - codechecks
cache:
yarn: true
directories:
  - node_modules
before_install:
  - yarn upgrade
install:
  - yarn
script:
  - yarn coveralls
