language: node_js
node_js: 15

branches:
only:
  - master
  - develop
  - codechecks
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/yarn
    - .next/cache
install:
  - yarn
script:
  - yarn coveralls
after_script:
  - yarn add -D @codechecks/client @codechecks/build-size-watcher @codechecks/lighthouse-keeper typecov -W
  - yarn build
  - yarn codechecks
